### PR TITLE
Ndv short script check slurm

### PR DESCRIPTION
**Pull request by NicoDeVeaux**
Micro-script that checks if you have KVS, clones it if you don't, guarantees it is up-to-date if you do. 

It also sets slurm-related variables like rank and number of workers. 

To run:

```
./inferelator_runner_slurmless.sh <specific organism runner>.py
```

Example:
```
./inferelator_runner_slurmless.sh bsubtilis_bbsr_workflow_runner.py
```

### CODE REVIEW

**Comment by NicoDeVeaux** [comment]
@kostyat

**Comment by kostyat** [comment]
Thanks for the reminder! I'll try to test it out today.

**Comment by kostyat** [comment]
Yep, it runs for me. I had kvsstcp in the wrong directory, so it installed a new one in the right directory, set the permissions, and ran fine for both b subtilis and yeast, producing the same results as before

**Comment by AaronWatters** [comment]
This worked for me too.  My only reservation is that it has to run in the main repo directory, but I think this may be a larger issue with the project.  I will merge the pull request and post an issue about running from multiple directories.

**Pull request merged**
