### PR TITLE
Workflow outline

### PR DESCRIPTION
**Pull request by AaronWatters**
This is a workflow skeleton with stubs for testing purposes.

### CODE REVIEW

**Comment by NicoDeVeaux** [comment]
Looks good to me

**Comment by NicoDeVeaux** [comment]
I'm pulling this branch into my local development branch to see if I can create a workflow for the specific project I'm working on.

**Comment by NicoDeVeaux** [comment]
Hi Aaron, 

When I try to create a workflow object, I get the following error:

  File "~/Dev/inferelator_ng/inferelator_ng/workflow.py", line 12, in <module>
    from . import utils
ValueError: Attempted relative import in non-package

Are you thinking of packaging this up?

**Comment by AaronWatters** [comment]
The commits for this PR are included in #19 so I'm removing this PR for now with the expectation that #19 will be merged.

**Pull request closed without merging**
