### PR TITLE
New workflow for making the gold standard from a 50/50 split in the p…

### PR DESCRIPTION
**Pull request by NicoDeVeaux**
…rior 
@dayanne-castro

### CODE REVIEW

**Comment by NicoDeVeaux** [comment]
Next step... adding unit tests

**Comment by kostyat** [comment]
Looks good (by eye), but I would add `np.random.seed(42)` or something in `set_gold_standard_and_priors` to set the random seed for reproducibility.

**Comment by kostyat** [comment]
I just ran it, and everything worked, but I got an aupr of 0.244 for B. subtilis. Which is very low. In R, I normally get an AUPR of at least 0.4 on the 50% leave-out set....

UPD: I ran it with 50 bootstraps (instead of 2) and tau=20 (instead of 45, which was suboptimal), and still got AUPR=0.31. I wonder why it's so much lower than with the R code.

**Comment by kostyat** [comment]
With Dayanne's suggestion, I realized that the discrepancy in performance was due to the difference in how emit_results is implemented, as compared to evaluate.R. When I calculated precision and recall using the R code, I got a similar result to what I got from R runs on B. subtilis.

As for the random seed thing, I realized my suggestion was not necessary, because the seed is already set in workflow.py. So the results should already be reproducible. If it's not reproducible for some reason, we could add `np.random.seed(self.random_seed)` to  `set_gold_standard_and_priors`.

In any case, I think this pull request is good to go. We should merge it, unless we need to add more unit tests.

**Comment by NicoDeVeaux** [comment]
thanks @kostyat

**Pull request merged**
