### PR TITLE
Ndv design response del tmin bug

### PR DESCRIPTION
**Pull request by NicoDeVeaux**
@dayanne-castro Fix to the python logic. I think using the right data structure would make this better

### CODE REVIEW

**Comment by dayanne-castro** [comment]
@nickdeveaux I think I need some explanation on what happened here haha :)

**Comment by NicoDeVeaux** [comment]
Little by little I've been pythonifying design_response_translation.py .

**Comment by NicoDeVeaux** [comment]
@dayanne-castro trying to make design_response faster and more readable. For example, by adding columns to the existing pandas dataframes, this new code is more efficient and more terse than the old code that used to create new pandas dataframes inside the loop

**Comment by NicoDeVeaux** [comment]
This pull request is being replaced by https://github.com/simonsfoundation/inferelator_ng/pull/60

**Pull request closed without merging**
