### PR TITLE
Bbsr refactor

### PR DESCRIPTION
**Pull request by tymor22**
this isn't ready quite yet

### CODE REVIEW

**Comment by dayanne-castro** [comment]
Should we delete the R stuff before implementing parallelization?

Dayanne

**Comment by kostyat** [comment]
@dayanne-castro , well it looks like bayesianRegression.R is deleted in this pull request, and the only thing that's left is the MI step. But as we discussed, so far we don't have a strategy for avoiding that R code. So what R code are you talking about?

Or are you saying, rather, that we should keep bayesianRegression.R before we implement parallelization, so that we can test the new one against the old one when both are parallelized? That would sound reasonable to me. Also, I can't quite remember, but it seems to me that at our last meeting we decided to keep the R version for now (that is, just to keep the file in the directory for benchmarking purposes, but obviously replace it with the python code in the default pipeline).

**Comment by dayanne-castro** [comment]
Yeah, we had decided that we should keep the R code only in history -- but for people like me that actively use the BBSR code, maybe it would not be ideal to have the master branch without parallelization.

I just realized what we were actually talking about last week, sorry. Anyway, I am fixing a few things and hopefully can check whether this runs fine tomorrow.

**Comment by NicoDeVeaux** [comment]
Hey, there's a separate branch with parallelization (using the KVS codebase being developed by the computing core at Flatiron) that's not quite ready yet. How about we wait to merge them both into master at the same time? This branch here has the goal of correctly implementing bbsr in Python, without parallelization

**Comment by kostyat** [comment]
Okay update: so I downloaded the pull request changes on my machine and ran nosetests. Everything ran fine, but I got a couple of warnings:

> /home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py:302: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
>   bs_betas.ix[res['ind'],X.index.values[res['pp']]] = res['betas']

> /home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py:303: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
>   bs_betas_resc.ix[res['ind'],X.index.values[res['pp']]] = res['betas_resc']

> ../home/tchoko09/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
>   warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)

> ..............S................................................../home/tchoko09/inferelator_ng/inferelator_ng/tfa.py:44: UserWarning: 1 transcription factors are removed because no expression or prior information exists.
>   warnings.warn(message)
> ..................

> ----------------------------------------------------------------------
> Ran 85 tests in 11.742s
> 
> OK (SKIP=1)

It seems that "1 transcription factors are removed because no expression or prior information exists." is intentional because I got the same message before downloading the pull request code.

Also, before, we used to 86 tests, and now we only have 85. Did we lose one of the unit tests?

**Comment by kostyat** [comment]
Wait, @nickdeveaux , doesn't it make sense to merge this one in first before merging the parallelization one? So that we can test out the parallelization code with the new bbsr_python.py code?

Also, more importantly, I don't see how parallelization affects BBSR (or whether or not it does at all), since parallelization is done outside of BBSR (at least in the R code). That is, we parallelize the function that calls the BBSR code, but it's done outside of the BBSR code. So I don't see why parallelization would affect keeping or removing the R version of bbsr. If it runs the same as the R version and gives the same results, then it would act the same way with parallelization. Right? Am I missing something?

**Comment by kostyat** [comment]
Okay, so I tried running bsubtilis_bbsr_workflow_runner.py. But it looks like I got an error that traces to line 229 in bbsr_python.py . That is, it's an exception for the case in which bic[i] = np.inf (i'm assuming that means infinity in numpy). Is anyone else getting this?

Here is the full output:

tchoko09@neumann:~/inferelator_ng$ python bsubtilis_bbsr_workflow_runner.py 
Creating design and response matrix ... 
Setting up TFA specific response matrix ... 
Computing Transcription Factor Activity ... 
Bootstrap 1 of 2
Calculating MI, Background MI, and CLR Matrix
Calculating betas using BBSR
('Progress: BBSR for gene', 0, '\n')
('Progress: BBSR for gene', 100, '\n')
('Progress: BBSR for gene', 200, '\n')
('Progress: BBSR for gene', 300, '\n')
('Progress: BBSR for gene', 400, '\n')
('Progress: BBSR for gene', 500, '\n')
('Progress: BBSR for gene', 600, '\n')
('Progress: BBSR for gene', 700, '\n')
('Progress: BBSR for gene', 800, '\n')
('Progress: BBSR for gene', 900, '\n')
('Progress: BBSR for gene', 1000, '\n')
('Progress: BBSR for gene', 1100, '\n')
('Progress: BBSR for gene', 1200, '\n')
('Progress: BBSR for gene', 1300, '\n')
('Progress: BBSR for gene', 1400, '\n')
('Progress: BBSR for gene', 1500, '\n')
('Progress: BBSR for gene', 1600, '\n')
('Progress: BBSR for gene', 1700, '\n')
('Progress: BBSR for gene', 1800, '\n')
('Progress: BBSR for gene', 1900, '\n')
('Progress: BBSR for gene', 2000, '\n')
('Progress: BBSR for gene', 2100, '\n')
Traceback (most recent call last):
  File "bsubtilis_bbsr_workflow_runner.py", line 10, in <module>
    workflow.run() 
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_tfa_workflow.py", line 39, in run
    current_betas, current_rescaled_betas = self.regression_driver.run(X, Y, self.clr_matrix, self.priors_data)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 298, in run
    x = BBSR(X, Y, clr_mat, nS, no_pr_val, weights_mat, prior_mat, cores)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 54, in BBSR
    OneGene=BBSRforOneGeneWrapper(i)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 13, in BBSRforOneGeneWrapper
    def BBSRforOneGeneWrapper(ind): return BBSRforOneGene(ind, gx, gy, gpp, gwm, gns)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 92, in BBSRforOneGene
    betas = BestSubsetRegression(y, x, g)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 130, in BestSubsetRegression
    bics = ExpBICforAllCombos(y, x, g, combos)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bbsr_python.py", line 229, in ExpBICforAllCombos
    raise ValueError('')
ValueError

**Comment by dayanne-castro** [comment]
I can only imagine that is happening because for some gene the variance of the residuals is 0... either this gene is constant or the model fits completely the training data... I have been thinking about this because I also use some formulation of BIC, but I haven't decided what to do yet

**Comment by kostyat** [comment]
I would think so too, unless there is something more boring going on. If everyone is getting the same error, I would think it would have to do with the variance going to 0. But it is strange that we never had this problem in R implementation, even though there is also a step that gives an error in ExpBICforAllCombos if the system is computationally singular.

Also, just having a perfect prediction, in which the model fits the data perfectly, would not result in an infinite BIC. To get an infinite BIC, you would need the rate to be zero, but the rate is calculated as

(SSR + (bhat-0)' * (X' * X /(1+g)) * (bhat - 0) )/2

So we need SSR == 0 (i.e. a perfect fit) AND  ( either bhat == 0 OR X' * X == 0 )

One way this is possible is if the gene is just constant. Another way this is possible is that we have a perfect fit and the predictor matrix is all zeros. Sounds like the first scenario is more likely. But I don't how it could be that in R we never had that problem. I don't think there were any precautions against completely constant genes...

**Comment by NicoDeVeaux** [comment]
If our goal is to have master be code that will execute grn inference fast on a cluster, merging bbsr_refactor into master without parallelization isn't an option.

**Comment by dayanne-castro** [comment]
Also, why is travis failing?

**Comment by NicoDeVeaux** [comment]
actually, @dayanne-castro travis is passing, but codecov dropped under 90%:
codecov/patch — 88.73% of diff hit (target 91.29%)

**Comment by AaronWatters** [comment]
Try changing the "except:" to "except KeyboardInterrupt as e:" to see what
source error causes this.

**Pull request closed without merging**
