### PR TITLE
New workflows

### PR DESCRIPTION
**Pull request by NicoDeVeaux**
@AaronWatters @marioluisao @kostyat 
A demonstration workflow for B. Subtilis using TFA (in python), MI-CLR & BBSR (in R).

While working on this, I discovered a problem in how we were creating design and response matrices in python: we weren't converting null values to NA properly. I added a test for that in test_design_response_R. 

This highlights some of the pros and cons of our refactoring scheme. **Pros**: more modularity leads to simplicity in the bootstrap loop. The .run() functionality of the workflow is simple and concise. 
**Cons**: Having to maintain dependencies for the R code; limited transparency into the legacy R code. 

ToDos: Right now, the output of the regression gets dumped into a timestamped output folder in the data/bsubtilis directory. It would be great to expand the emit_results function (@kostyat and I were talking about this today). Feel free to fork this branch

### CODE REVIEW

**Comment by NicoDeVeaux** [comment]
There's no testing coverage on my specific workflow class, Bsubtilis_Bbsr_Workflow. My opinion is that these workflows themselves don't require testing, unless they've become universal enough that they're being subclassed by other users.

**Comment by dayanne-castro** [comment]
Makes sense!

**Comment by NicoDeVeaux** [comment]
Here's how to run it:

```
cd inferelator_ng
python bsubtilis_bbsr_workflow_runner.py
```

Could I get some comments on this pull request? I'd like to get your feedback before I start creating similar workflows for my current project

**Comment by AaronWatters** [comment]
It looks like the bsubtilis_bbsr_workflow_runner.py is missing.  Please add it @nickdeveaux

**Comment by NicoDeVeaux** [comment]
Maybe you're not seeing it because it's a directory up?  file location: https://github.com/nickdeveaux/inferelator_ng/blob/1e170b2ba60cefb9f0f20e48922708ab951f6dc6/bsubtilis_bbsr_workflow_runner.py

**Comment by AaronWatters** [comment]
oops.  Sorry.  I think it should not be at the top level but should be moved to a subdirectory, maybe `./runners`.

**Comment by NicoDeVeaux** [comment]
@AaronWatters do you think I should assume that the runner script will be run from this new runners directory? Or should I keep the import paths and file paths relative to the top-level inferelator_ng dir?

**Comment by kostyat** [comment]
I'm wondering why the parameters (that we would normally have in one file in the jobs directory) are scattered between two files (in different folders): input_dir, number of bootstraps, delTmax/min and tau are in bsubtilis_bbsr_workflow_runner.py, and everything else is in inferelator_ng/workflow.py.

I guess the logic was that the file names (expression.tsv, tfs.tsv, meta_data.tsv, gold_standard.tsv) are going to be the same regardless of organism (which is why you didn't put it in inferelator_ng/bsubtilis_bbsr_workflow.py), whereas the input directory, number of bootstraps, delTmax/min and tau maybe changed within one organism in order to optimize parameters, increase statistical significance etc. I'm not sure why the input directory would need to be changed in such a circumstance, but I imagine that if a developer wants to try to compare two different gold standards for the same expression data, they can do it in the current framework by creating two input folders, each of them containing all relevant input files, with the gold standard file differing between the two folders.

However, the drawback to this is that if one is to try multiple gold standards, and also if one wants to use a different file for a prior file than for the gold standard, one would have to have a lot of repeated folders. The number of folders can furthermore become intractable if you're working on something for months or years, adding new gold standards etc. I prefer keeping all of my gold standards in one folder and then changing the file path to the gold standard, expression data, etc as I go. This also applies if I have multiple expression clusters and am running the Inferelator on each of them separately. I don't want to have to name all of those files "expression.tsv", I would prefer keeping them as "expression-cluster1.tsv" etc, and keeping them all in the same folder, rather than creating 4 folders for 4 expression clusters and calling 4 different files "cluster1/expression.tsv", "cluster2/expression.tsv" etc. (and keep in mind that with the current setup all of these folders will also have to contain gold_standard.tsv, and if I want to test different say 3 gold standards with the clusters, I have to create 12 different files, each of them with "expression.tsv" and "gold_standard.tsv" files which all mean different things depending on which folder they are in).

So this is why I don't think expression_matrix_file, tf_names_file, meta_data_file, priors_file, and gold_standard_file should be defined in inferelator_ng/workflow.py, which is a generic file that is high level and should not be touched very much by a user and even a developer. It should probably be in inferelator_ng/bsubtilis_bbsr_workflow.py or even bsubtilis_bbsr_workflow_runner.

Basically workflows replace the old "jobs" idea. The thing about jobs is that in the end you'd have a lot of them - one for every setup that you're doing. Maybe workflow files should also be in a separate folder, like we did for jobs?

In the end, I actually gave up making more jobs because their number was becoming too big and I was forgetting which one is which. Instead, I set all parameters in the jobs file that I had to change a lot (expression data, gold standard, tau, random seed, input directory, and tf file) to NULL and defined a higher level bash file (sometimes even 2 levels of them) that defined all kinds of parameters in different ways (such as when you need to loop over expression clusters, loop over gold standards, loop over values of tau etc). I found that saving each combination of parameters as a separate job is not very practical, and that I'd rather change those 2 higher-level bash files every time and save them together with the output. But I'm not sure if this is the best solution.

**Comment by AaronWatters** [comment]
My only strong feeling about where to put the driver files is not at the top level.
I think maybe it makes sense to put them in the same directory with the data.
We also could assume that the inferelator is installed globally or in a virtual environment
using

```
python setup.py install
```

So it could be imported anywhere.

**Comment by NicoDeVeaux** [comment]
@kostyat Thanks for bringing this up. The general idea is that yes, the workflow.py is a general class and has settings that are going to be the same regardless of organism. However, if you did want to change one of these settings, you can by over-writing that variable in the specific workflow that you build. For example, I could have overwritten workflow.tf_names_file = 'new_file' in bsubtilis_bbsr_workflow_runner.py. You would not need to modify workflow.py in that case.

The example you bring up is interesting: what if you want to use multiple expression files, but store them in one file? Then your new workflow should re-implement the function `def get_data(self):` . Its re-implementation would not modify workflow.py, but would overwrite that method to allow, for example, reading in 3 goldstandards and multiple expression datasets from the same file. 

We'll likely want to use a majority rule to decide if something belongs in workflow.py or not. If more than 50% of the new workflows that inherit from WorkflowBase change the same piece of code from WorkflowBase then it no longer belongs in WorkflowBase

**Comment by kostyat** [comment]
Oh, I understand how it works now. I like it: this way you can also override compute_common_data in case you want to change the way the design and response matrix is calculated, for example.

I guess we can still be flexible about what goes in the workflow.py file. I would think for example that the stuff inside compute_common_data should go in the workflow.py file, although we are going to modify each of those steps. But the beauty of this design is that we can have an underlying "default" inferelator in the workflow.py and at the same time be able to modify it on a higher level and override it.

I also liked that you split computing design and response into two separate steps. That will be useful when creating workflows that alter one of these two steps but not both of them.

However, when I tried running the code as you specified on my computer, I got the following error:

```
Creating design and response matrix ... 
Traceback (most recent call last):
  File "bsubtilis_bbsr_workflow_runner.py", line 10, in <module>
    workflow.run() 
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bsubtilis_bbsr_workflow.py", line 28, in run
    self.compute_common_data()
  File "/home/tchoko09/inferelator_ng/inferelator_ng/bsubtilis_bbsr_workflow.py", line 53, in compute_common_data
    (self.design, self.response) = drd.run(self.expression_matrix, self.meta_data)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/design_response_R.py", line 59, in run
    exp = utils.convert_to_R_df(expression_data_frame)
  File "/home/tchoko09/inferelator_ng/inferelator_ng/utils.py", line 21, in convert_to_R_df
    for col in new_df.select_dtypes(include=[bool]):
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 1815, in __getattr__
    (type(self).__name__, name))
AttributeError: 'DataFrame' object has no attribute 'select_dtypes'
```

**Comment by NicoDeVeaux** [comment]
Hmm we must have different versions of pandas. My pandas version has the function select_dtypes (this is used when converting pandas data frames to R data frames). I think the way to fix this will involve setting a minimum version of pandas in the requirements.txt file. I'll look into it.

**Comment by kostyat** [comment]
I have the latest version of pandas, 0.13.1, and I am running python 2.7

**Comment by NicoDeVeaux** [comment]
Added a line in requirements.txt forcing you to upgrade to the version of pandas I know has this function ( >= 0.18)

**Comment by kostyat** [comment]
oh oops, you are right, 13.1 is not the latest version at all!

**Comment by kostyat** [comment]
I upgraded pandas, and now everything runs. Everything looks good. I think I will merge the pull request, or do you want more feedback from other people?

**Comment by NicoDeVeaux** [comment]
I think there's still one thing we should decide before merging the pull request. What functions in the bsubtilis workflow class are general enough that they should be moved to WorkflowBase? I think the compute_common_data might be a good candidate

**Comment by NicoDeVeaux** [comment]
Another issue I've just run into -- storing the expression.tsv files on github means that we're storing large files, in the MBs, on github. For human data sets, I've run into the 100MB limit. We could potentially store the data files in a seperate repository,  maybe using git large file storage: https://git-lfs.github.com./

**Comment by kostyat** [comment]
I agree that we are going to run into a space issue, but I think that can be a separate discussion, maybe under "issues".

I also think compute_common_data should be moved into WorkflowBase. That means that its dependency filter_prior_matrix should also be moved to WorkflowBase.

**Comment by kostyat** [comment]
Here is another issue: there needs to be a separate function (although it could be a part of emit_results, I guess, but in the old version it's not a part of evaluate.R) that combines the rescaled betas into a combined confidence score. This is done in the inferelator by adding the rescaled betas matrices.

I don't think in general it is good to create a separate tsv file of betas and resc.betas for every bootstrap. The way we do it in R is that we create an RData file that contains a list of these data frames. Is it possible to do something like that in python? Or do you think the old RData approach is confusing to the user? I've found that a lot of people seem to be confused about what those files are and what to do with them. On the other hand, if we make a good enough emit_results function, the user would hopefully not have to worry about having to open these intermediate matrices. But of course the user will want to have a network -- and that's a different discussion.

**Comment by kostyat** [comment]
Oh, and bootstrap numbers should start from 1, not from 0. Just a small detail. It doesn't make sense when it counts: "bootstrap 0 out of 5, bootstrap 1 out of 5... bootstrap 4 out of 5"
And do we want to scrap printing out "calculating gene 100, calculating gene 200" etc? I always found that pretty nice but it does not necessarily bear any function.

**Comment by NicoDeVeaux** [comment]
@kostyat I agree with your comments. I will add a new class called ResultsProcessor that has functions `compute_combined_confidences`, `threshold_and_summarize`, and `calculate_aupr`. It will be called by the `emit_results` function in workflow base.

**Comment by kostyat** [comment]
Hey Nick,

There is a bug in your threshold_and_summarize function in the results_processor.py file. The bug is on line 33. What the code currently does is that across the list of betas (each of which is a matrix of betas) it selects the entries that appear as non-zero for more than _threshold_ fraction of times, and then puts all of those values into one list, ignoring all the zeros... I'm having trouble explaining it in text form, but basically it's just not doing the right thing at all. Here is an example.

define beta in the following way:
`beta1 = pd.DataFrame(np.array([[1, 0], [1, 0]]), ['gene1', 'gene2'], ['tf1','tf2'])`
`beta2 = pd.DataFrame(np.array([[1, 0], [1, 2]]), ['gene1', 'gene2'], ['tf1','tf2'])`
`betas = [beta1, beta2]`

Then we see that tf1->gene1 and tf1->gene2 appear as non-zero twice, tf2->gene2 appears as non-zero once, and all other betas always appear as a zero. Let's say the threshold is 0.5. Then what the current code does is that it keeps tf1->gene1 and tf1->gene2, and binds the two vectors ([1,1] from beta1 and [1,1] from beta2) together into a 2-by-2 vector. To me, that does not make any sense to do. Furthermore, this sometimes results in errors because the dimensions do not match (it's just a coincidence that in this case they matched).

I think what we want to do for this step is first produce a matrix that shows for every tf-gene interaction how many times it appeared as non-zero, and then another matrix that has zeros whenever the number in the first matrix is less than a certain threshold, and 1 otherwise. I don't really know how to write that in python but it shouldn't be hard so I'll be working on that now.

**Comment by dayanne-castro** [comment]
Hi everyone,

I actually modify my inferelator code to not cut at a threshold -- that
means that the .tsv file could also be used to calculate precision and
recall (could even have these values as columns).

Just some thoughts!

**Comment by kostyat** [comment]
Everything looks good to me (and runs without problems on my computer), and I like the network.tsv file output.

**Comment by NicoDeVeaux** [comment]
ok, merging.

**Pull request merged**
