### PR TITLE
Got the tests work on Windows

### PR DESCRIPTION
**Pull request by ryi06**
## Got the tests work on Windows. Add changes to upstream master Windows branch

Ran 23 tests in 3.793s

OK (SKIP=1)

### CODE REVIEW

**Comment by AaronWatters** [comment]
I think maybe the best thing to do is to add an operating system check.

```
if os.name == "posix":
    subprocess.check_output(command, shell=True)
...
```

Let me try to submit a pull request to your pull request...

**Comment by ryi06** [comment]
Nosetests generate a bunch of R code for every test it runs (example below). Not sure if it's correct.

R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> source('C:/Users/ryi06/OneDrive/BonneauLab/inferelator_ng/inferelator_ng/R_code/design_and_response.R')
> 
> meta.data <- read.table('C:/Users/ryi06/OneDrive/BonneauLab/inferelator_ng/inferelator_ng/tests/artifacts/meta_data.csv', sep = ',', header = 1, row.names = 1)
> exp.mat <- read.table('C:/Users/ryi06/OneDrive/BonneauLab/inferelator_ng/inferelator_ng/tests/artifacts/exp_mat.csv', sep = ',', header = 1, row.names = 1)
> delT.min <- 2
> delT.max <- 4
> tau <- 2
> dr <- design.and.response(meta.data, exp.mat, delT.min, delT.max, tau)
> #dr$final_response_matrix
> #dr$final_design_matrix
> 
> write.table(as.matrix(dr$final_response_matrix), 'C:/Users/ryi06/OneDrive/BonneauLab/inferelator_ng/inferelator_ng/tests/artifacts/response.tsv', sep = '\t')
> write.table(as.matrix(dr$final_design_matrix), 'C:/Users/ryi06/OneDrive/BonneauLab/inferelator_ng/inferelator_ng/tests/artifacts/design.tsv', sep = '\t')
> cat("done. \n")
> done.

**Comment by AaronWatters** [comment]
I editted this to  https://github.com/simonsfoundation/inferelator_ng/pull/11 -- please check that it works for you on Windows.

**Comment by AaronWatters** [comment]
@ryi06 -- Please check out #11 (which supercedes this PR) and if ok approve it.
I fixed the failing tests issue.  Thanks!  -- Aaron Watters

**Pull request closed without merging**
